import './globals.css'

import type { Metadata } from 'next'

import { MONTHS } from '@/constants/month'

import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Camara Cerro Cora',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const month = new Date().getMonth()
  const currentTheme = MONTHS[month]

  return (
    <html
      lang="pt-BR"
      className="antialiased"
      data-theme={currentTheme}
      suppressHydrationWarning
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
